spring:
  rabbitmq:
    port: 5672
    host: 114.116.233.39
    virtual-host: /ead
    username: admin
    password: 123456
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: animer-service
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.233.39:3306/ead
    username: root
    password: lmx200wx
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  #  session:
  #    timeout: 86400
  #    store-type: redis
  # redis 配置
#  redis:
#    port: 6379
#    host: 192.168.253.129
#    database: 0
#    password: 123456
server:
  port: 80
  servlet:
    context-path: /api


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

file:
  pre: E:\javaProject2023\ead\files\

ipaddress:
  #  huawei: 114.116.233.39
  huawei: 127.0.0.1

baidu:
  AppId: 31261127
  ApiKey: 0cCbuBkegoTlhA1ykAbSD7v4
  SecretKey: dgMjAu4EndQpAdw8ap3Tn3x4wG8HmQ5e


baiduimage:
  AppId: 28150947
  ApiKey: ymFaLFGtu3o5MK4CdDjXERBf
  SecretKey: S07GnTZEFVlH0R3eIZV9pSUlFeQkWHjS

qiniu:
  accessKey: j62JgoY3YH4qlPDXWuh-eVDLA-ykn89FOEGypuIH
  secretKey: stAvnzTLh9c0-sh_Ts8nkN-hn9B5H3ldxbCnEVQR
  preurl: http://image.tsjsjxxc.top/

openai:
  token: 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
  timeout: 5000
proxy:
  host: 127.0.0.1
  port: 10809
#
#
#  http://127.0.0.1/api/document?id=1;




